language: ruby
rvm: 2.3.1
jdk: orclejdk8

install:
  - gem ubdate --system
  - gem --version
  - bundle instal
script:
  - jekyll build
  - htmlproofer ./_site --check-html --check-fivicon

  env:
      global:
        -NOKOGIRI_USE_SYSTEM_LIBERIES_=true
